using System;
using System.Linq;
using System.Collections.Generic;
using StarkInfra.Utils;


namespace StarkInfra
{
    public partial class BusinessAccountRequest
    {
        /// <summary>
        /// BusinessAccountRequest.Log object
        /// <br/>
        /// Every time a BusinessAccountRequest entity is modified, a corresponding BusinessAccountRequest.Log
        /// is generated for the entity. This log is never generated by the
        /// user, but it can be retrieved to check additional information
        /// on the BusinessAccountRequest.
        /// <br/>
        /// Properties:
        /// <list>
        ///     <item>ID [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
        ///     <item>Request [BusinessAccountRequest]: BusinessAccountRequest entity to which the log refers to.</item>
        ///     <item>Errors [list of dictionaries]: list of errors linked to this BusinessAccountRequest event</item>
        ///     <item>Type [string]: type of the BusinessAccountRequest event which triggered the log creation. ex: "created", "processing", "approved", "denied", "failed"</item>
        ///     <item>Created [DateTime]: creation DateTime for the log. ex: DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
        /// </list>
        /// </summary>
        public class Log : Resource
        {
            public BusinessAccountRequest Request { get; }
            public List<Dictionary<string, object>> Errors { get; }
            public string Type { get; }
            public DateTime Created { get; }

            /// <summary>
            /// BusinessAccountRequest.Log object
            /// <br/>
            /// Every time a BusinessAccountRequest entity is modified, a corresponding BusinessAccountRequest.Log
            /// is generated for the entity. This log is never generated by the
            /// user, but it can be retrieved to check additional information
            /// on the BusinessAccountRequest.
            /// <br/>
            /// Attributes (return-only):
            /// <list>
            ///     <item>id [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
            ///     <item>request [BusinessAccountRequest]: BusinessAccountRequest entity to which the log refers to.</item>
            ///     <item>errors [list of dictionaries]: list of errors linked to this BusinessAccountRequest event</item>
            ///     <item>type [string]: type of the BusinessAccountRequest event which triggered the log creation. ex: "created", "processing", "approved", "denied", "failed"</item>
            ///     <item>created [DateTime]: creation DateTime for the log. ex: DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
            /// </list>
            /// </summary>
            public Log(string id, DateTime created, string type, List<Dictionary<string, object>> errors, BusinessAccountRequest request) : base(id)
            {
                Request = request;
                Errors = errors;
                Type = type;
                Created = created;
            }

            /// <summary>
            /// Retrieve a specific BusinessAccountRequest.Log by its id
            /// <br/>
            /// Receive a single BusinessAccountRequest.Log object previously created by the Stark Infra API by its id
            /// <br/>
            /// Parameters (required):
            /// <list>
            ///     <item>id [string]: object unique id. ex: "5656565656565656"</item>
            /// </list>
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>BusinessAccountRequest.Log object that corresponds to the given id.</item>
            /// </list>
            /// </summary>
            public static Log Get(string id, User user = null)
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetId(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    id: id,
                    user: user
                ) as Log;
            }

            /// <summary>
            /// Retrieve BusinessAccountRequest.Log objects
            /// <br/>
            /// Receive an IEnumerable of BusinessAccountRequest.Log objects previously created in the Stark Infra API
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35</item>
            ///     <item>after [DateTime, default null] date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null] date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter for log event types. ex: new List&lt;string&gt;{ "created", "processing", "approved", "denied", "failed" }</item>
            ///     <item>accountRequestIds [list of strings, default null]: list of BusinessAccountRequest ids to filter logs. ex: new List&lt;string&gt;{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>IEnumerable of BusinessAccountRequest.Log objects with updated attributes</item>
            /// </list>
            /// </summary>
            public static IEnumerable<Log> Query(
                int? limit = null, DateTime? after = null, DateTime? before = null, List<string> types = null,
                List<string> accountRequestIds = null, User user = null
            )
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetList(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "limit", limit },
                        { "after", after },
                        { "before", before },
                        { "types", types },
                        { "accountRequestIds", accountRequestIds }
                    },
                    user: user
                ).Cast<Log>();
            }

            /// <summary>
            /// Retrieve paged BusinessAccountRequest.Log objects
            /// <br/>
            /// Receive a list of up to 100 BusinessAccountRequest.Log objects previously created in the Stark Infra API and the cursor to the next page.
            /// Use this function instead of query if you want to manually page your requests.
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>cursor [string, default null]: cursor returned on the previous page function call</item>
            ///     <item>limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50</item>
            ///     <item>after [DateTime, default null] date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null] date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter for log event types. ex: new List&lt;string&gt;{ "created", "processing", "approved", "denied", "failed" }</item>
            ///     <item>accountRequestIds [list of strings, default null]: list of BusinessAccountRequest ids to filter logs. ex: new List&lt;string&gt;{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>list of BusinessAccountRequest.Log objects with updated attributes</item>
            ///     <item>cursor to retrieve the next page of BusinessAccountRequest.Log objects</item>
            /// </list>
            /// </summary>
            public static (List<Log> page, string pageCursor) Page(
                string cursor = null, int? limit = null, DateTime? after = null, DateTime? before = null,
                List<string> types = null, List<string> accountRequestIds = null, User user = null
            )
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                (List<StarkCore.Utils.SubResource> page, string pageCursor) = Rest.GetPage(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "cursor", cursor },
                        { "limit", limit },
                        { "after", after },
                        { "before", before },
                        { "types", types },
                        { "accountRequestIds", accountRequestIds }
                    },
                    user: user
                );
                List<Log> logs = new List<Log>();
                foreach (StarkCore.Utils.SubResource subResource in page)
                {
                    logs.Add(subResource as Log);
                }
                return (logs, pageCursor);
            }

            internal static (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) Resource()
            {
                return (resourceName: "BusinessAccountRequestLog", resourceMaker: ResourceMaker);
            }

            internal static Utils.Resource ResourceMaker(dynamic json)
            {
                string id = json.id;
                BusinessAccountRequest request = BusinessAccountRequest.ResourceMaker(json.request);
                List<Dictionary<string, object>> errors = json.errors?.ToObject<List<Dictionary<string, object>>>();
                string type = json.type;
                string createdString = json.created;
                DateTime created = StarkCore.Utils.Checks.CheckDateTime(createdString);

                return new Log(id: id, request: request, errors: errors, type: type, created: created);
            }
        }
    }
}
