using System;
using System.Linq;
using System.Collections.Generic;
using StarkInfra.Utils;


namespace StarkInfra
{
    public partial class CreditNote
    {
        /// <summary>
        /// CreditNote.Log object
        /// <br/>
        /// Every time a CreditNote entity is updated, a corresponding CreditNote.Log 
        /// is generated for the entity. This log is never generated by the user, 
        /// but it can be retrieved to check additional information on the CreditNote.
        /// <br/>
        /// Properties:
        /// <list>
        ///     <item>ID [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
        ///     <item>Note [CreditNote]: CreditNote entity to which the log refers to.</item>
        ///     <item>Errors [list of strings]: list of errors linked to this CreditNote event</item>
        ///     <item>Type [string]: type of the CreditNote event which triggered the log creation. ex: "canceled", "updated", "expired", "failed", "refunded", "registered", "sending", "sent", "signed", "success"</item>
        ///     <item>Created [DateTime]: Created DateTime for the log. ex: DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
        /// </list>
        /// </summary>
        public class Log : Resource
        {
            public CreditNote Note { get; }
            public List<Dictionary<string, object>> Errors { get; }
            public string Type { get; }
            public DateTime Created { get; }

            /// <summary>
            /// CreditNote.Log object
            /// <br/>
            /// Every time a CreditNote entity is updated, a corresponding CreditNote.Log 
            /// is generated for the entity. This log is never generated by the user, 
            /// but it can be retrieved to check additional information on the CreditNote.
            /// <br/>
            /// Attributes (return-only):
            /// <list>
            ///     <item>id [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
            ///     <item>note [CreditNote]: CreditNote entity to which the log refers to.</item>
            ///     <item>errors [list of strings]: list of errors linked to this CreditNote event</item>
            ///     <item>type [string]: type of the CreditNote event which triggered the log creation. ex: "canceled", "updated", "expired", "failed", "refunded", "registered", "sending", "sent", "signed", "success"</item>
            ///     <item>created [DateTime]: creation DateTime for the log. ex: DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
            /// </list>
            /// </summary>
            public Log(string id, CreditNote note, List<Dictionary<string, object>> errors, string type, DateTime created) : base(id)
            {
                Note = note;
                Errors = errors;
                Type = type;
                Created = created;
            }

            /// <summary>
            /// Retrieve a specific CreditNote.Log
            /// <br/>
            /// Receive a single CreditNote.Log object previously updated by the Stark Infra API by passing its id
            /// <br/>
            /// Parameters (required):
            /// <list>
            ///     <item>id [string]: CreditNote unique id. ex: "5656565656565656"</item>
            /// </list>
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>user [Organization/Project object]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>CreditNote.Log object with updated attributes</item>
            /// </list>
            /// </summary>
            public static Log Get(string id, User user = null)
            {
                (string resourceName, Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetId(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    id: id,
                    user: user
                ) as Log;
            }

            /// <summary>
            /// Retrieve CreditNote.Log objects
            /// <br/>
            /// Receive an IEnumerable of CreditNote.Log objects previously created in the Stark Infra API
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35</item>
            ///     <item>after [DateTime, default null]: date filter for objects updated only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null]: date filter for objects updated only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter for log event types. ex: new List<string>{ "canceled", "updated", "expired", "failed", "refunded", "registered", "sending", "sent", "signed", "success" }</item>
            ///     <item>noteIds [list of strings, default null]: list of CreditNote ids to filter logs. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.User.Default was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>IEnumerable of CreditNote.Log objects with updated attributes</item>
            /// </list>
            /// </summary>
            public static IEnumerable<Log> Query(int? limit = null, DateTime? after = null, DateTime? before = null,
                List<string> types = null, List<string> ids = null, List<string> noteIds = null, User user = null)
            {
                (string resourceName, Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetList(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "noteIds", noteIds }
                    },
                    user: user
                ).Cast<Log>();
            }

            /// <summary>
            /// Retrieve paged CreditNote.Log
            /// <br/>
            /// Receive a list of up to 100 CreditNote.Log objects previously updated in the Stark Infra API and the cursor to the next page.
            /// Use this function instead of query if you want to manually page your notes.
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>cursor [string, default null]: cursor returned on the previous page function call</item>
            ///     <item>limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35.</item>
            ///     <item>after [DateTime, default null]: date filter for objects updated only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null]: date filter for objects updated only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: new List<string>{ "canceled", "updated", "expired", "failed", "refunded", "registered", "sending", "sent", "signed", "success" }</item>
            ///     <item>noteIds [list of strings, default null]: list of CreditNote ids to filter retrieved objects. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.User.Default was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>list of CreditNote.Log objects with updated attributes</item>
            ///     <item>cursor to retrieve the next page of CreditNote.Log objects</item>
            /// </list>
            /// </summary>
            public static (List<Log> page, string pageCursor) Page(string cursor = null, int? limit = null, DateTime? after = null,
                DateTime? before = null, List<string> types = null, List<string> ids = null, List<string> noteIds = null, User user = null)
            {
                (string resourceName, Api.ResourceMaker resourceMaker) = Resource();
                (List<SubResource> page, string pageCursor) = Rest.GetPage(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "cursor", cursor },
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "noteIds", noteIds }
                    },
                    user: user
                );
                List<Log> logs = new List<Log>();
                foreach (SubResource subResource in page)
                {
                    logs.Add(subResource as Log);
                }
                return (logs, pageCursor);
            }

            internal static (string resourceName, Utils.Api.ResourceMaker resourceMaker) Resource()
            {
                return (resourceName: "CreditNoteLog", resourceMaker: ResourceMaker);
            }

            internal static Utils.Resource ResourceMaker(dynamic json)
            {
                string id = json.id;
                CreditNote note = CreditNote.ResourceMaker(json.note);
                List<Dictionary<string, object>> errors = json.errors.ToObject<List<Dictionary<string, object>>>();
                string type = json.type;
                string createdString = json.created;
                DateTime created = Checks.CheckDateTime(createdString);

                return new Log(id: id, note: note, errors: errors, type: type, created: created);
            }
        }
    }
}
