using System;
using System.Linq;
using System.Collections.Generic;
using StarkInfra.Utils;


namespace StarkInfra
{
    public partial class PixInternalTransactionReport
    {
        /// <summary>
        /// PixInternalTransactionReport.Log object
        /// <br/>
        /// Every time a PixInternalTransactionReport entity is modified, a corresponding
        /// PixInternalTransactionReport.Log is generated for the entity. This log is never
        /// generated by the user.
        /// <br/>
        /// Properties:
        /// <list>
        ///     <item>ID [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
        ///     <item>Report [PixInternalTransactionReport]: PixInternalTransactionReport entity to which the log refers to.</item>
        ///     <item>Type [string]: type of the PixInternalTransactionReport event which triggered the log creation. ex: "created", "failed", "sent", "success"</item>
        ///     <item>Errors [list of dictionaries]: list of errors linked to this PixInternalTransactionReport event.</item>
        ///     <item>Created [DateTime]: creation DateTime for the log. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
        /// </list>
        /// </summary>
        public class Log : Resource
        {
            public PixInternalTransactionReport Report { get; }
            public string Type { get; }
            public List<Dictionary<string, object>> Errors { get; }
            public DateTime? Created { get; }

            /// <summary>
            /// PixInternalTransactionReport.Log object
            /// <br/>
            /// Every time a PixInternalTransactionReport entity is modified, a corresponding
            /// PixInternalTransactionReport.Log is generated for the entity. This log is never
            /// generated by the user.
            /// <br/>
            /// Attributes (return-only):
            /// <list>
            ///     <item>id [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
            ///     <item>report [PixInternalTransactionReport]: PixInternalTransactionReport entity to which the log refers to.</item>
            ///     <item>type [string]: type of the PixInternalTransactionReport event which triggered the log creation. ex: "created", "failed", "sent", "success"</item>
            ///     <item>errors [list of dictionaries]: list of errors linked to this PixInternalTransactionReport event.</item>
            ///     <item>created [DateTime]: creation DateTime for the log. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
            /// </list>
            /// </summary>
            public Log(string id, PixInternalTransactionReport report, string type, List<Dictionary<string, object>> errors, DateTime? created) : base(id)
            {
                Report = report;
                Type = type;
                Errors = errors;
                Created = created;
            }

            /// <summary>
            /// Retrieve a specific PixInternalTransactionReport.Log by its id
            /// <br/>
            /// Receive a single PixInternalTransactionReport.Log object previously created by the Stark Infra API by passing its id
            /// <br/>
            /// Parameters (required):
            /// <list>
            ///     <item>id [string]: object unique id. ex: "5656565656565656"</item>
            /// </list>
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>PixInternalTransactionReport.Log object that corresponds to the given id.</item>
            /// </list>
            /// </summary>
            public static Log Get(string id, User user = null)
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetId(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    id: id,
                    user: user
                ) as Log;
            }

            /// <summary>
            /// Retrieve PixInternalTransactionReport.Log objects
            /// <br/>
            /// Receive an IEnumerable of PixInternalTransactionReport.Log objects previously created in the Stark Infra API
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35</item>
            ///     <item>after [DateTime, default null]: date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null]: date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: new List<string>{ "success", "failed" }</item>
            ///     <item>reportIds [list of strings, default null]: list of PixInternalTransactionReport ids to filter retrieved objects. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>ids [list of strings, default null]: Log ids to filter PixInternalTransactionReport.Log objects. ex: new List<string>{ "5656565656565656" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>IEnumerable of PixInternalTransactionReport.Log objects with updated attributes</item>
            /// </list>
            /// </summary>
            public static IEnumerable<Log> Query(int? limit = null, DateTime? after = null, DateTime? before = null,
                List<string> types = null, List<string> reportIds = null, List<string> ids = null, User user = null)
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetList(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "reportIds", reportIds },
                        { "ids", ids }
                    },
                    user: user
                ).Cast<Log>();
            }

            /// <summary>
            /// Retrieve paged PixInternalTransactionReport.Log objects
            /// <br/>
            /// Receive a list of up to 100 PixInternalTransactionReport.Log objects previously created in the Stark Infra API and the cursor to the next page.
            /// Use this function instead of query if you want to manually page your requests.
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>cursor [string, default null]: cursor returned on the previous page function call</item>
            ///     <item>limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35.</item>
            ///     <item>after [DateTime, default null]: date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null]: date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: new List<string>{ "success", "failed" }</item>
            ///     <item>reportIds [list of strings, default null]: list of PixInternalTransactionReport ids to filter retrieved objects. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>ids [list of strings, default null]: Log ids to filter PixInternalTransactionReport.Log objects. ex: new List<string>{ "5656565656565656" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>list of PixInternalTransactionReport.Log objects with updated attributes</item>
            ///     <item>cursor to retrieve the next page of PixInternalTransactionReport.Log objects</item>
            /// </list>
            /// </summary>
            public static (List<Log> page, string pageCursor) Page(string cursor = null, int? limit = null,
                DateTime? after = null, DateTime? before = null, List<string> types = null, List<string> reportIds = null,
                List<string> ids = null, User user = null)
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                (List<StarkCore.Utils.SubResource> page, string pageCursor) = Rest.GetPage(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "cursor", cursor },
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "reportIds", reportIds },
                        { "ids", ids }
                    },
                    user: user
                );
                List<Log> logs = new List<Log>();
                foreach (StarkCore.Utils.SubResource subResource in page)
                {
                    logs.Add(subResource as Log);
                }
                return (logs, pageCursor);
            }

            internal static (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) Resource()
            {
                return (resourceName: "PixInternalTransactionReportLog", resourceMaker: ResourceMaker);
            }

            internal static Utils.Resource ResourceMaker(dynamic json)
            {
                string id = json.id;
                PixInternalTransactionReport report = PixInternalTransactionReport.ResourceMaker(json.report);
                string type = json.type;
                List<Dictionary<string, object>> errors = json.errors.ToObject<List<Dictionary<string, object>>>();
                string createdString = json.created;
                DateTime created = StarkCore.Utils.Checks.CheckDateTime(createdString);

                return new Log(
                    id: id, report: report, type: type, errors: errors, created: created
                );
            }
        }
    }
}
