using System;
using System.Linq;
using System.Collections.Generic;
using StarkInfra.Utils;


namespace StarkInfra
{
    public partial class IndividualAccountAttachment
    {
        /// <summary>
        /// IndividualAccountAttachment.Log object
        /// <br/>
        /// Every time an IndividualAccountAttachment entity is modified, a corresponding
        /// IndividualAccountAttachment.Log is generated for the entity. This log is never generated by the user.
        /// <br/>
        /// Properties:
        /// <list>
        ///     <item>ID [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
        ///     <item>Attachment [IndividualAccountAttachment]: IndividualAccountAttachment entity to which the log refers to.</item>
        ///     <item>Type [string]: type of the IndividualAccountAttachment event which triggered the log creation. Options: "created", "success", "failed", "deleted"</item>
        ///     <item>Errors [list of dictionaries]: list of errors linked to this IndividualAccountAttachment event.</item>
        ///     <item>Created [DateTime]: creation DateTime for the log. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
        /// </list>
        /// </summary>
        public class Log : Resource
        {
            public IndividualAccountAttachment Attachment { get; }
            public string Type { get; }
            public List<Dictionary<string, object>> Errors { get; }
            public DateTime Created { get; }

            /// <summary>
            /// IndividualAccountAttachment.Log object
            /// <br/>
            /// Attributes (return-only):
            /// <list>
            ///     <item>id [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
            ///     <item>attachment [IndividualAccountAttachment]: IndividualAccountAttachment entity to which the log refers to.</item>
            ///     <item>type [string]: type of the IndividualAccountAttachment event which triggered the log creation. ex: "created"</item>
            ///     <item>errors [list of dictionaries]: list of errors linked to this IndividualAccountAttachment event.</item>
            ///     <item>created [DateTime]: creation DateTime for the log. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
            /// </list>
            /// </summary>
            public Log(string id, IndividualAccountAttachment attachment, string type, List<Dictionary<string, object>> errors, DateTime created) : base(id)
            {
                Attachment = attachment;
                Type = type;
                Errors = errors;
                Created = created;
            }

            /// <summary>
            /// Retrieve a specific IndividualAccountAttachment.Log by its id
            /// <br/>
            /// Receive a single IndividualAccountAttachment.Log object previously created by the Stark Infra API by passing its id
            /// <br/>
            /// Parameters (required):
            /// <list>
            ///     <item>id [string]: object unique id. ex: "5656565656565656"</item>
            /// </list>
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>IndividualAccountAttachment.Log object that corresponds to the given id.</item>
            /// </list>
            /// </summary>
            public static Log Get(string id, User user = null)
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetId(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    id: id,
                    user: user
                ) as Log;
            }

            /// <summary>
            /// Retrieve IndividualAccountAttachment.Log objects
            /// <br/>
            /// Receive an IEnumerable of IndividualAccountAttachment.Log objects previously created in the Stark Infra API
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35</item>
            ///     <item>after [DateTime, default null]: date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null]: date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: new List<string>{ "created" }</item>
            ///     <item>attachmentIds [list of strings, default null]: list of IndividualAccountAttachment ids to filter retrieved objects. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>IEnumerable of IndividualAccountAttachment.Log objects with updated attributes</item>
            /// </list>
            /// </summary>
            public static IEnumerable<Log> Query(int? limit = null, DateTime? after = null, DateTime? before = null,
                List<string> types = null, List<string> attachmentIds = null, User user = null)
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetList(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "attachmentIds", attachmentIds }
                    },
                    user: user
                ).Cast<Log>();
            }

            /// <summary>
            /// Retrieve paged IndividualAccountAttachment.Log objects
            /// <br/>
            /// Receive a list of up to 100 IndividualAccountAttachment.Log objects previously created in the Stark Infra API and the cursor to the next page.
            /// Use this function instead of query if you want to manually page your requests.
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>cursor [string, default null]: cursor returned on the previous page function call</item>
            ///     <item>limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35.</item>
            ///     <item>after [DateTime, default null]: date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null]: date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: new List<string>{ "created" }</item>
            ///     <item>attachmentIds [list of strings, default null]: list of IndividualAccountAttachment ids to filter retrieved objects. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>list of IndividualAccountAttachment.Log objects with updated attributes</item>
            ///     <item>cursor to retrieve the next page of IndividualAccountAttachment.Log objects</item>
            /// </list>
            /// </summary>
            public static (List<Log> page, string pageCursor) Page(string cursor = null, int? limit = null, DateTime? after = null,
                DateTime? before = null, List<string> types = null, List<string> attachmentIds = null, User user = null)
            {
                (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
                (List<StarkCore.Utils.SubResource> page, string pageCursor) = Rest.GetPage(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "cursor", cursor },
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "attachmentIds", attachmentIds }
                    },
                    user: user
                );
                List<Log> logs = new List<Log>();
                foreach (StarkCore.Utils.SubResource subResource in page)
                {
                    logs.Add(subResource as Log);
                }
                return (logs, pageCursor);
            }

            internal static (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) Resource()
            {
                return (resourceName: "IndividualAccountAttachmentLog", resourceMaker: ResourceMaker);
            }

            internal static Utils.Resource ResourceMaker(dynamic json)
            {
                string id = json.id;
                IndividualAccountAttachment attachment = (IndividualAccountAttachment)IndividualAccountAttachment.ResourceMaker(json.attachment);
                string type = json.type;
                List<Dictionary<string, object>> errors = json.errors is null ? new List<Dictionary<string, object>> { } : json.errors.ToObject<List<Dictionary<string, object>>>();
                string createdString = json.created;
                DateTime created = StarkCore.Utils.Checks.CheckDateTime(createdString);

                return new Log(
                    id: id, attachment: attachment, type: type, errors: errors, created: created
                );
            }
        }
    }
}
